package com.example.educor_app.Authentications;

import android.content.Context;
import android.content.Intent;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import com.airbnb.lottie.LottieAnimationView;
import com.example.educor_app.Classroom.Classrooms;
import com.example.educor_app.R;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.ArrayList;
import java.util.List;

public class RegisterFormActivity extends AppCompatActivity {
    EditText name,email,phone_number,institution;
    TextView qualification;
    Button submit;
    Spinner spinner;
    String Qualification;
    FirebaseDatabase database;
    DatabaseReference myRef;
    FirebaseAuth mAuth;
    public static String Mail;
    public static String Username;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_register_form);

        submit=findViewById(R.id.Submit);
        name=findViewById(R.id.Name);
        email=findViewById(R.id.Email);
        phone_number=findViewById(R.id.Phone_Number);
        institution=findViewById(R.id.Institution);
        spinner=findViewById(R.id.Spinner);

        mAuth = FirebaseAuth.getInstance();

        Username = getIntent().getStringExtra("Name");
        Mail = getIntent().getStringExtra("Mail");
        email.setText(Mail);
        name.setText(Username);


        //Spinner code starts
        List<String> categories=new ArrayList<>();
        categories.add("Qualification");
        categories.add("Student");
        categories.add("Teacher");

        ArrayAdapter<String> dataAdapter;
        dataAdapter=new ArrayAdapter(this,android.R.layout.simple_spinner_item,categories);

        dataAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);

        spinner.setAdapter(dataAdapter);
        spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {

                if(parent.getItemAtPosition(position).equals("Qualification")){
                    //do nothing
                    Qualification=null;
                }
                else{
                    //on selecting sppiner item
                    String item=parent.getItemAtPosition(position).toString();
                    //anything u want do here
                    Qualification=spinner.getSelectedItem().toString();
                }
            }

            @Override
            public void onNothingSelected(AdapterView<?> parent) {
                //TODO AUTOGENERATED METHOD DO HERE

            }
        });
        //spinner code ends

        submit.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                checkConnection();
            }
        });
    }
    public void checkConnection(){
        ConnectivityManager manager=(ConnectivityManager) getApplicationContext().getSystemService(Context.CONNECTIVITY_SERVICE);

        NetworkInfo activeNetwork= manager.getActiveNetworkInfo();
        if (null==activeNetwork){
            Intent intent=new Intent(RegisterFormActivity.this,network_indicator.class);
            intent.putExtra("from","RegisterFormActivity");
            startActivity(intent);
            finish();
        }else{

            FirebaseUser user=FirebaseAuth.getInstance().getCurrentUser();


            final String Name=Username.toString();
            final String Email=Mail.toString();
            final String Phone_number=phone_number.getText().toString();
            final String Institution=institution.getText().toString();

            if(name.length()==0){
                name.setError("Enter Name!");
            }else if(email.length()==0){
                email.setError("Enter Email!");
            }else if(phone_number.length()==0){
                phone_number.setError("Enter Phone Number!");
            }else if(institution.length()==0){
                institution.setError("Enter Institution!");
            } else if(Qualification==null){
                Toast.makeText(RegisterFormActivity.this, " select Qualification",
                        Toast.LENGTH_SHORT).show();
            }else{
                final signup info=new signup(Name,Email,Phone_number,Institution,Qualification,user.getUid());

                FirebaseDatabase.getInstance().getReference("signup").child(mAuth.getCurrentUser().getUid())
                        .setValue(info).addOnCompleteListener(new OnCompleteListener<Void>() {
                    @Override
                    public void onComplete(@NonNull Task<Void> task) {

                        submit.setVisibility(View.INVISIBLE);
                        final LottieAnimationView lottie_submit=findViewById(R.id.lottie_Submit);
                        lottie_submit.setScale(0.4f);

                        lottie_submit.setVisibility(View.VISIBLE);
                        lottie_submit.setSpeed(1);
                        lottie_submit.playAnimation();

                        Thread timer = new Thread() {
                            public void run() {
                                try {
                                    sleep(3000);
                                } catch (InterruptedException e) {
                                    e.printStackTrace();
                                } finally {


                                    final users info=new users(Name,Email,Phone_number,Qualification,user.getUid());
                                    FirebaseDatabase.getInstance().getReference("users").child(mAuth.getCurrentUser().getUid())
                                            .setValue(info).addOnCompleteListener(new OnCompleteListener<Void>() {
                                        @Override
                                        public void onComplete(@NonNull Task<Void> task) {
                                            Intent intent=new Intent(RegisterFormActivity.this, Classrooms.class);
                                            startActivity(intent);
                                            finish();
                                        }
                                        });


                                }
                            }
                        };
                        timer.start();

                    }
                });
            }
          /*  */
        }
    }
}